name: pokedex
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  infinite_scroll_pagination: ^4.1.0
  provider: ^6.1.2
  image_picker: ^1.1.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_gen: ^5.3.0
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/pokemon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
